### ISSUE TITLE
10/11

### ISSUE THREAD

**Issue by Pzdrs** [Bahamut731lp/sem2-srcs#1]
matlab neumim ani kokot
![image](https://user-images.githubusercontent.com/57369536/165551386-521bef17-858d-419e-98f6-f8604efa5fc3.png)
nabizim panaka kdyz to fixnes

**Comment by Bahamut731lp** [comment]
more hoď tam tohle

```matlab
%Když to je jenom konstanta, tak nemá smysl tady dělat fuckin schéma
if (length(p) == 1)
     x = p(1);
     return;
end
```

edit: a nebo prostě vrať to, co po tobě ten test chce - když to je konstanta, vrať to prázdný lol

**Comment by Bahamut731lp** [comment]
![image](https://user-images.githubusercontent.com/27443880/165581961-b7287637-390d-4265-a0bb-76f0c5cab351.png)
A taky se zdá, že máš nějak fucked test - nešmátřáš do proměnných někde jinde? Resp. jestli někde omylem nepřepisuješ proměnný, který ten vymrdanej codecritic používá

**Comment by Pzdrs** [comment]
jo mrdnul jsem tam ten length check ale nelibilo se mu ze x ma actually nejakou hodnout takze prazdnou matici chtel. id say that counts as fixed tak pak rekni a dame speeda ve snejkovi nebo nekde
